# Site settings
title: 'Shujon Shikto'
description: 'Security researcher'
url: 'https://shikto.me'
google_analytics: 'UA-135476618-1'

author:
  name:  'Shujon Shikto'
  email: nustransfer@icloud.com
  twitter_username: shiktochy
  facebook_username: vmadcc
  medium_username: shujonshikto
  linkedin_username:  shujon-shikto-44780782

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
